### PR TITLE
Add " require 'simple_form' " in template.

### PR DESCRIPTION
**Pull request by sachinswagh**

### CODE REVIEW

**Comment by feliperenan** [comment]
Hi @sachinswagh, thanks for the pull-request.

Could you please explain the motivation behind this change?

**Comment by sachinswagh** [comment]
To avoid uninitialized constant error.

**Comment by sachinswagh** [comment]
@feliperenan : If you don't feel any need. You can close the pull request.

**Comment by feliperenan** [comment]
Did you have some use case that you had to require Simple Form?

**Comment by rafaelfranca** [comment]
In a Rails application, the gem is required when you add the `gem` call in the `Gemfile`. That may not be true if people changes the away bundler works in a Rails application, but we don't need to support that case.

**Pull request closed without merging**
