### PR TITLE
remove Fixnum and Bignum deprecated warning

### PR DESCRIPTION
**Pull request by takkanm**
Fixnum and Bignum is deprecated at Ruby2.4.

https://github.com/ruby/ruby/blob/v2_4_0/NEWS#L288

### CODE REVIEW

**Comment by janpieper** [comment]
What about shortening the change and adding a comment?

```ruby
basic_objects = [String, Integer, Float, NilClass, Symbol, TrueClass, FalseClass]
basic_objects += [Fixnum, Bignum] unless unified_intger_version? # Ruby <= 2.3.x compatibility
```

**Comment by takkanm** [comment]
@janpieper Thanks. It looks good to me. I'll fix it.

**Comment by lucasmazza** [comment]
@takkanm thanks!

**Comment by takkanm** [comment]
:smile:

**Pull request merged**
