### PR TITLE
Use latest Ruby version in CI

### PR DESCRIPTION
**Pull request by takkanm**
I added test setting for Ruby2.4.
And, any Ruby version updated to latest version.

### CODE REVIEW

**Comment by jcoyne** [comment]
It looks like Nokogiri 1.7.0 is not compatible with ruby < 2.2, so you'll have to pin nokogiri version in the Gemfile or drop those older rubies from the build matrix.

**Comment by oliverklee** [comment]
Related: I've added PR #1455 to remove support for the unmaintained Ruby 1.9.x.

**Comment by lucasmazza** [comment]
Closed by #1454

**Comment by takkanm** [comment]
I see. Thank you !!

**Pull request closed without merging**
