### PR TITLE
fixed typos and indentations for _form generators

### PR DESCRIPTION
**Pull request by aoozdemir**
As titled.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Thank you for the pull request but those are not types. They need to be that way to generate valid code.

**Comment by aoozdemir** [comment]
That's interesting. Can you explain a bit more, esp. double %?

**Comment by rafaelfranca** [comment]
`<%%=` in the template will generate `<%=` in the view. `<%` is executed at template evaluation time so `<% attribute.each` we want to execute at template evaluation time and not in the generated code. Because of this it is not indented like the generated code.

**Comment by aoozdemir** [comment]
Oh, I understand it now. `<%%=` is for escaping the interpolation. Didn't know that was a valid erb. But why is slim's indentation different than others?

**Comment by rafaelfranca** [comment]
There is no reason really, the result is the same.

**Comment by aoozdemir** [comment]
Alright! Thanks for the clarification. #TIL

**Pull request closed without merging**
