### PR TITLE
Add ability to set an error_class directly on input

### PR DESCRIPTION
**Pull request by CharlieHawker**
Relates to issue #1475

### CODE REVIEW

**Comment by remofritzsche** [comment]
Just wanted to create a PR this second for the exact same thing, but your solution is way more elegant. Would be wonderful if this gets merged and released :) Thank you for your work!

**Comment by remofritzsche** [comment]
I've tried your patch and just found a bug: This code is adding a class to `wrapper_options[:class]`. This hash is shared between requests and statically cached, so changing this very instance creates adds the error class to all the inputs on second form reload and persists. 

A simple solution is to add `wrapper_options = wrapper_options.dup` right after the line `if wrapper_options`.

Now it works like a charm :)

**Comment by CharlieHawker** [comment]
Good spot @remofritzsche, I'd been merrily using my branch without noticing that! 

I've implemented your suggestion, but with a slight amendment – I put it inside the second conditional block (the one that checks for the existence of the `:error_class` option) so as to not do the `wrapper_options.dup` unnecessarily.

**Comment by airblade** [comment]
@CharlieHawker Doesn't this add the `error_class` to all inputs, even if only one has an error?

**Comment by CharlieHawker** [comment]
@airblade it shouldn't do. @remofritzsche did raise an issue with the PR which I have since fixed (see earlier in the thread). Are you experiencing what he described?

**Comment by remofritzsche** [comment]
I also couldn't notice this. I'm using the current patch for quite some time now and have never experienced any issues (though I'd love to see this for `input_field` as well).

**Comment by anlek** [comment]
@CharlieHawker, Thanks for taking this on, seems like Bootstrap 4 beta could use this feature.

**Comment by CharlieHawker** [comment]
@remofritzsche agreed, I need to sort that `input_field` bit out. Will try to do it this weekend.

**Comment by Superpencil** [comment]
@CharlieHawker #pokethebear

**Comment by m5o** [comment]
@CharlieHawker would you also add some tests, @rafaelfranca like them too 😬

**Comment by yordis** [comment]
@rafaelfranca hey man, do you think we can have this merge as soon as you can?

**Comment by printercu** [comment]
I've tried this patch, seems like it does work only in inline mode (`f.input :email, error_class: 'is-invalid'`) but does not work for wrappers defined in initializers with `b.use :input, error_class: 'is-invalid`. In this case it adds `error_class='is-invalid'` attr to valid fields, and when using with `class: 'form-control'` it expands this string with every new error (like this: `form-control is-invalid is-invalid is-invalid string email optional`), also making all other inputs `is-invalid`.

I've slightly modified it and implemented with patch like this:

```ruby
SimpleForm::Inputs::Base.prepend Module.new {
  def merge_wrapper_options(options, wrapper_options)
    if wrapper_options&.key?(:error_class)
      wrapper_options = wrapper_options.dup
      error_class = wrapper_options.delete(:error_class)
      wrapper_options[:class] = "#{wrapper_options[:class]} #{error_class}" if has_errors?
    end
    super(options, wrapper_options)
  end
}
```

**Comment by feliperenan** [comment]
Hi @CharlieHawker 

Are you going to work on it yet?

**Comment by m5o** [comment]
ℹ️ fyi, currently the `aria-required` attr. is added to an input with error.

https://github.com/plataformatec/simple_form/blob/7059550a5d841909f3fd3122f2b757ed2c9f1544/lib/simple_form/components/html5.rb#L9-L18

Here It would be easy to add additional class, don't know if this is a bad hack

```diff
input_html_options[:'aria-invalid']  = has_errors? || nil
+ input_html_options[:class] << 'is-invalid' if has_errors?
```

**Comment by rafaelfranca** [comment]
That is definitely the wrong place 😄. I'm fine with this change with proper tests.

**Comment by feliperenan** [comment]
I have continued this PR here #1552

**Comment by feliperenan** [comment]
Closing in favor #1552

**Pull request closed without merging**
